apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

metadata:
  namespace: staging

bases:
  - ../../kustomize/base

patches:
  - patches/backend-patch.yaml
  - patches/frontend-patch.yaml

resources:
  - secrets-depl.yaml

commonLabels:
  project: devops

namePrefix: vector-
